services:
  proxy-ssh:
    image: quay.io/devdockops/autossh
    network_mode: host
    pull_policy: always
    container_name: proxy-ssh
    restart: always
    environment:
      - SISH_TCP_ALIAS=true
      - SISH_NOTE="ssh proxy avviato su gh-test-vm"
    command: -o SendEnv=SISH_NOTE -o SendEnv=SISH_TCP_ALIAS -p 443 -R gh-proxy:2222:localhost:22 prx.adiprint.it
