services:
  superdufs-app:
    image: fabiop85/superdufs:player
    pull_policy: always
    container_name: superdufs-app
    restart: always
    volumes:
      - data:/data
      - resume:/opt/playback-resume
    command: >-
      /data
      -A
      -a admin:test2026@/:rw
      --playback-resume-enabled=true
      --playback-resume-dir=/opt/playback-resume
      --publink-enabled
      --enable-data-stats
      --show-concurrent-uploads-settings
      --resilient-player-max-retry=20
      --resilient-player-reconnect-interval=10

volumes:
  data:
  resume: